//
//  MainViewController.swift
//  MamsyTestTask
//
//  Created by  Kostantin Zarubin on 21.07.2018.
//  Copyright (c) 2018  Kostantin Zarubin. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MainViewControllerInput {
    func displayResult(viewModel: MainScene.getResult.ViewModel)
}

protocol MainViewControllerOutput {
    func getResult(number: PrimeNumber)
}

class MainViewController: UIViewController, MainViewControllerInput {
    
    var output: MainViewControllerOutput?
    var router: MainRouter?
    
    @IBOutlet weak var maxNumberTextField: UITextField!
    @IBOutlet weak var sumResultLabel: UILabel!
    @IBOutlet weak var primeNumbersTextView: UITextView!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        MainConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        sumResultLabel.isHidden = true
    }
    
    // MARK: Display logic
    
    func displayResult(viewModel: MainScene.getResult.ViewModel) {
        sumResultLabel.isHidden = false
        sumResultLabel.text = viewModel.number == 0 ? "N должен быть > 1" : "Сумма простых чисел: \(String(viewModel.number))"
        
        let stringArray = viewModel.array.map { (int) -> String in
            return String(" \(int) ")}.joined()
        primeNumbersTextView.text = stringArray
    }
    
    // MARK: UI events
    
    @IBAction func getSumResultAction(_ sender: UIButton) {
        output?.getResult(number: PrimeNumber(maxNumber: Int(maxNumberTextField.text!)!, numbersList: []))
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension MainViewController: MainPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
