//
//  MainPresenter.swift
//  MamsyTestTask
//
//  Created by  Kostantin Zarubin on 21.07.2018.
//  Copyright (c) 2018  Kostantin Zarubin. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol MainPresenterInput {
    func presentResult(response: MainScene.getResult.Response)
}

protocol MainPresenterOutput: class {
    func displayResult(viewModel: MainScene.getResult.ViewModel)
}

class MainPresenter: MainPresenterInput {
    
    weak var output: MainPresenterOutput?
    
    func presentResult(response: MainScene.getResult.Response) {
        let number = response.primeNumber
        
        let viewModel = mapToViewModel(number: number)
        output?.displayResult(viewModel: viewModel)
    }
    
    // MARK: Presentation logic
    func mapToViewModel(number: PrimeNumber) -> MainScene.getResult.ViewModel {
        return MainScene.getResult.ViewModel(number: number.maxNumber, array: number.numbersList)
    }
}
