//
//  MainModels.swift
//  MamsyTestTask
//
//  Created by  Kostantin Zarubin on 21.07.2018.
//  Copyright (c) 2018  Kostantin Zarubin. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct MainScene {
    struct getResult {
        
        struct Response {
            var primeNumber: PrimeNumber
        }
        
        struct ViewModel {
            let number: Int
            let array: [Int]
        }
    }
}
