//
//  MainRouter.swift
//  MamsyTestTask
//
//  Created by  Kostantin Zarubin on 21.07.2018.
//  Copyright (c) 2018  Kostantin Zarubin. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MainRouterInput {
    
}

protocol MainRouterDataSource: class {
    
}

protocol MainRouterDataDestination: class {
    
}

class MainRouter: MainRouterInput {
    
    weak var viewController: MainViewController!
    weak private var dataSource: MainRouterDataSource!
    weak var dataDestination: MainRouterDataDestination!
    
    init(viewController: MainViewController, dataSource: MainRouterDataSource, dataDestination: MainRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
