//
//  MainOrderWorker.swift
//  MamsyTestTask
//
//  Created by  Kostantin Zarubin on 21.07.2018.
//  Copyright (c) 2018  Kostantin Zarubin. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import Foundation

class MainWorker {

    func calculations(number: PrimeNumber) -> PrimeNumber {
        var result = [Int]()
        guard number.maxNumber >= 2 else { return PrimeNumber(maxNumber:0, numbersList: [])}
        var composite = [Bool](repeating: false, count: number.maxNumber + 1)
        for i in 2...number.maxNumber {
            if !composite[i] {
                result.append(i)
                for multiple in stride(from: i * i, through: number.maxNumber, by: i) {
                    composite[multiple] = true
                }
            }
        }
        return PrimeNumber(maxNumber: result.reduce(0, +), numbersList: result)
    }
}
