//
//  MainConfigurator.swift
//  MamsyTestTask
//
//  Created by  Kostantin Zarubin on 21.07.2018.
//  Copyright (c) 2018  Kostantin Zarubin. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension MainInteractor: MainViewControllerOutput, MainRouterDataSource, MainRouterDataDestination {
    
}

extension MainPresenter: MainInteractorOutput {
}

class MainConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = MainConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: MainViewController) {
        
        let presenter = MainPresenter()
        presenter.output = viewController
        
        let interactor = MainInteractor()
        interactor.output = presenter
        
        let router = MainRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
